# Generated by Django 3.0.4 on 2020-06-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
