# Generated by Django 3.0.4 on 2020-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.IntegerField(choices=[(0, 'Owner'), (1, 'Pet Lover'), (2, 'Animal Shelter')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.IntegerField(default=0),
        ),
    ]
