# Generated by Django 3.0.4 on 2020-06-29 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adtool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('url_link', models.URLField(default='')),
                ('criteria', models.IntegerField(choices=[(0, 'Adoption'), (1, 'Caretaking'), (2, 'Fostering')], default=0)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisementlog',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='advertisementlog',
            name='site',
        ),
        migrations.RemoveField(
            model_name='website',
            name='user',
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.DeleteModel(
            name='AdvertisementLog',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
