# Generated by Django 3.0.4 on 2020-06-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0002_auto_20200630_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listedpet',
            name='url_link',
        ),
    ]
