# Generated by Django 3.0.4 on 2020-06-30 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0003_remove_listedpet_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedpet',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='listedpet',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date activity end'),
        ),
        migrations.AddField(
            model_name='listedpet',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date activity start'),
        ),
    ]
