# Generated by Django 3.0.4 on 2020-06-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adtool', '0004_auto_20200630_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedpet',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
